import { Inter } from "next/font/google"
import { AuthProvider } from "@/contexts/AuthProvider"
import Notification from "@/components/Notification"
import "./globals.css"
import AppProvider from "@/contexts/AppProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      <body className={`h-full ${inter.className}`}>
        <AppProvider>
          <Notification />
          <AuthProvider>{children}</AuthProvider>
        </AppProvider>
      </body>
    </html>
  )
}
